// primus-core/src/setup.rs
//
// First-run interactive setup wizard.
//
// On first launch (when `.primus_config.toml` does not exist), this module
// guides the operator through three questions:
//
//   1. Is this node a Seed Node?  (yes / no)
//   2. What is the public IP this node is reachable on?  (auto-detect or manual)
//   3. Are there existing Seed Nodes to bootstrap from?  (list of IPs)
//
// The answers are written to `.primus_config.toml` in the working directory
// and returned as `NodeConfig` so `async_main` can act on them without
// prompting again on restarts.
//
// PLATFORM NOTES
//   - Ubuntu server: the external IP is detected via `ip route get 8.8.8.8`
//     falling back to `curl https://ipinfo.io/ip`.
//   - Windows: resolved via `WinHTTP`-less Rust (reqwest not available here —
//     we use only stdlib and tokio), falling back to manual entry.

use std::io::{self, Write};
use std::net::{IpAddr, SocketAddr};
use std::path::Path;

const CONFIG_FILE: &str = ".primus_config.toml";

// ── Public config struct ──────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct NodeConfig {
    /// True if this node is designated as a public seed node.
    pub is_seed: bool,

    /// The public-facing IP for this node (used to build PrimusNR).
    /// On a normal peer, this is the UPnP/NAT-discovered external IP.
    /// On a seed node it is explicitly set by the operator.
    pub public_ip: Option<IpAddr>,

    /// TCP port this node will listen on (defaults to 9000).
    pub port: u16,

    /// List of seed nodes to dial on startup.
    pub seed_peers: Vec<SocketAddr>,

    /// Optional real domain or IP for TLS certificate.
    pub tls_domain: Option<String>,
}

impl NodeConfig {
    /// Try to load config from `.primus_config.toml`.
    /// Returns `None` if the file does not exist (first run).
    pub fn load() -> Option<Self> {
        let path = Path::new(CONFIG_FILE);
        if !path.exists() {
            return None;
        }
        let text = std::fs::read_to_string(path).ok()?;
        Self::parse_toml(&text)
    }

    /// Save config to `.primus_config.toml`.
    pub fn save(&self) {
        let seeds_str: Vec<String> = self.seed_peers.iter().map(|s| s.to_string()).collect();
        let content = format!(
            r#"# Primus-Core node configuration — auto-generated by setup wizard.
# Edit manually or delete to re-run the wizard on next startup.

is_seed = {}
public_ip = "{}"
port = {}
seed_peers = [{}]
tls_domain = "{}"
"#,
            self.is_seed,
            self.public_ip.map(|ip| ip.to_string()).unwrap_or_default(),
            self.port,
            seeds_str
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", "),
            self.tls_domain.as_deref().unwrap_or("localhost")
        );
        if let Err(e) = std::fs::write(CONFIG_FILE, content) {
            eprintln!("⚠️  Could not save config: {}", e);
        }
    }

    fn parse_toml(text: &str) -> Option<Self> {
        let mut is_seed = false;
        let mut public_ip: Option<IpAddr> = None;
        let mut port: u16 = 9000;
        let mut seed_peers: Vec<SocketAddr> = Vec::new();
        let mut tls_domain: Option<String> = None;

        for line in text.lines() {
            let line = line.trim();
            if line.starts_with('#') || line.is_empty() {
                continue;
            }
            if let Some(val) = line.strip_prefix("is_seed = ") {
                is_seed = val.trim() == "true";
            } else if let Some(val) = line.strip_prefix("public_ip = ") {
                let s = val.trim().trim_matches('"');
                if !s.is_empty() {
                    public_ip = s.parse().ok();
                }
            } else if let Some(val) = line.strip_prefix("port = ") {
                port = val.trim().parse().unwrap_or(9000);
            } else if let Some(val) = line.strip_prefix("seed_peers = [") {
                let inner = val.trim().trim_end_matches(']');
                for entry in inner.split(',') {
                    let addr_str = entry.trim().trim_matches('"');
                    if let Ok(addr) = addr_str.parse::<SocketAddr>() {
                        seed_peers.push(addr);
                    }
                }
            } else if let Some(val) = line.strip_prefix("tls_domain = ") {
                let s = val.trim().trim_matches('"');
                if !s.is_empty() && s != "localhost" {
                    tls_domain = Some(s.to_string());
                }
            }
        }

        Some(Self { is_seed, public_ip, port, seed_peers, tls_domain })
    }
}

// ── Setup wizard ─────────────────────────────────────────────────────────────

/// Run the first-run wizard. Blocks on stdin — must be called before
/// the tokio runtime starts async tasks that use stdin.
pub fn run_wizard(port: u16) -> NodeConfig {
    let os = detect_os();

    println!();
    println!("╔══════════════════════════════════════════════════════════════╗");
    println!("║         🌌  PRIMUS-CORE — FIRST TIME SETUP WIZARD           ║");
    println!("╚══════════════════════════════════════════════════════════════╝");
    println!("  OS detected : {}", os);
    println!("  Config will be saved to  →  {}", CONFIG_FILE);
    println!();

    // ── Q1: Seed node? ───────────────────────────────────────────────────────
    let is_seed = prompt_yes_no(
        "❓ Is this node a public SEED NODE (stable, with public IP)?",
        false,
    );

    // ── Q2: Public IP ────────────────────────────────────────────────────────
    let public_ip: Option<IpAddr> = if is_seed {
        println!();
        println!("🌐 Detecting your public IP…");
        let auto_ip = detect_public_ip_sync();

        if let Some(ip) = auto_ip {
            println!("   Auto-detected: {}", ip);
            let use_auto = prompt_yes_no("   Use this IP?", true);
            if use_auto {
                Some(ip)
            } else {
                prompt_ip("   Enter public IP manually: ")
            }
        } else {
            println!("   ⚠️  Could not auto-detect external IP.");
            prompt_ip("   Enter public IP manually: ")
        }
    } else {
        None // regular peer — will use UPnP/NAT discovery at runtime
    };

    // ── Q3: Seed peers to connect to ─────────────────────────────────────────
    println!();
    let mut seed_peers: Vec<SocketAddr> = Vec::new();

    if is_seed {
        println!("ℹ️  This node IS a seed node. It will wait for other nodes to connect.");
        println!("   (Optional) You can still add other seed nodes to peer with:");
    } else {
        println!("🔗 Enter the seed node addresses to bootstrap from.");
    }
    println!("   Format: IP:PORT  (e.g. 203.0.113.10:9000)");
    println!("   Press Enter with empty input when done.");
    println!();

    loop {
        let input = prompt_line("   Add seed peer (or Enter to skip): ");
        if input.is_empty() {
            break;
        }
        match input.parse::<SocketAddr>() {
            Ok(addr) => {
                seed_peers.push(addr);
                println!("   ✅ Added: {}", addr);
            }
            Err(_) => {
                eprintln!("   ❌ Invalid format — expected IP:PORT (e.g. 1.2.3.4:9000)");
            }
        }
    }

    // ── Summary ──────────────────────────────────────────────────────────────
    println!();
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");
    println!("  Configuration summary:");
    println!("  Role       : {}", if is_seed { "🌱 Seed Node" } else { "🔗 Regular Peer" });
    println!("  Public IP  : {}", public_ip.map(|ip| ip.to_string()).unwrap_or_else(|| "auto (UPnP)".into()));
    println!("  TCP Port   : {}", port);
    println!("  Seed peers : {} configured", seed_peers.len());
    if !seed_peers.is_empty() {
        for s in &seed_peers {
            println!("               → {}", s);
        }
    }
    println!("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━");

    let config = NodeConfig { is_seed, public_ip, port, seed_peers, tls_domain: None };
    config.save();
    println!("  💾 Saved to {}", CONFIG_FILE);
    println!();

    config
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn detect_os() -> &'static str {
    if cfg!(target_os = "linux") {
        "Linux (Ubuntu/Debian recommended)"
    } else if cfg!(target_os = "windows") {
        "Windows"
    } else if cfg!(target_os = "macos") {
        "macOS"
    } else {
        "Unknown"
    }
}

fn prompt_line(prompt: &str) -> String {
    print!("{}", prompt);
    let _ = io::stdout().flush();
    let mut input = String::new();
    let _ = io::stdin().read_line(&mut input);
    input.trim().to_string()
}

fn prompt_yes_no(question: &str, default_yes: bool) -> bool {
    let hint = if default_yes { "[Y/n]" } else { "[y/N]" };
    loop {
        let answer = prompt_line(&format!("{}  {} ", question, hint));
        match answer.to_lowercase().as_str() {
            "" => return default_yes,
            "y" | "yes" => return true,
            "n" | "no" => return false,
            _ => eprintln!("   Please enter y or n."),
        }
    }
}

fn prompt_ip(prompt: &str) -> Option<IpAddr> {
    loop {
        let input = prompt_line(prompt);
        if input.is_empty() {
            return None;
        }
        match input.parse::<IpAddr>() {
            Ok(ip) => return Some(ip),
            Err(_) => eprintln!("   ❌ Invalid IP address. Try again (e.g. 203.0.113.10):"),
        }
    }
}

/// Attempt to detect the public IP synchronously via OS tools.
///
/// - Linux: `ip route get 8.8.8.8` → parses `src <IP>`.
/// - Windows: `netsh interface ip show address` → first "IP Address" line.
/// - Fallback: tries a simple TCP connect to 8.8.8.8:80 and reads local addr.
fn detect_public_ip_sync() -> Option<IpAddr> {
    // Best-effort fallback: connect to Google DNS and read local address.
    // This gives the LAN IP (which is what UPnP will expose for seed nodes
    // behind NAT). For a true seed, the operator should enter their public IP.
    if let Ok(socket) = std::net::UdpSocket::bind("0.0.0.0:0") {
        let _ = socket.connect("8.8.8.8:80");
        if let Ok(addr) = socket.local_addr() {
            let ip = addr.ip();
            if !ip.is_loopback() && !ip.is_unspecified() {
                return Some(ip);
            }
        }
    }

    // Linux: parse `ip route get 8.8.8.8`
    #[cfg(target_os = "linux")]
    if let Ok(output) = std::process::Command::new("ip")
        .args(["route", "get", "8.8.8.8"])
        .output()
    {
        let text = String::from_utf8_lossy(&output.stdout);
        // Output contains: "... src 192.168.1.5 uid ..."
        if let Some(src_idx) = text.find("src ") {
            let rest = &text[src_idx + 4..];
            let ip_str = rest.split_whitespace().next().unwrap_or("");
            if let Ok(ip) = ip_str.parse::<IpAddr>() {
                return Some(ip);
            }
        }
    }

    None
}
